spring:
  application:
    name: spring-boot
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "pg"
    password: "pg"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
